services:
  photograph:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    container_name: photograph
    command: "gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 photographApi.asgi:application"
